-- Dimension: securities (the investable instruments).
-- Grain: one row per security. Simple "Type 1" dimension - no history tracked,
-- values just reflect the current state of the instrument.

with securities as (
    select * from {{ ref('stg_securities') }}   -- read from the staging model, not the raw source
)

select
    -- Surrogate key: warehouse-owned key, generated by hashing the business key.
    -- Insulates fact joins from any change in the source's own IDs.
    {{ dbt_utils.generate_surrogate_key(['security_id']) }} as security_sk,

    security_id as security_bk,   -- business/natural key from the source system
    ticker,
    security_name,
    asset_class,
    sector,
    currency
from securities